create TABLE IF NOT EXISTS hits (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(100) NOT NULL,
    uri VARCHAR(256) NOT NULL,
    ip VARCHAR(25) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);